Models/ErrorViewModel.cs
namespace stonecutter.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Inventory.cs
namespace stonecutter.Models
{
    public class Inventory
    {
        public int Id { get; set; }
        public string? StoneType { get; set; }
        public int? Quantity { get; set; }
        public string? Name { get; set; }
        
        public DateTime DateTime { get; set; }
    }
}

Models/TimeTable.cs
using System.ComponentModel.DataAnnotations;

namespace stonecutter.Models
{
    public class TimeTable
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter your name")]
        public string? ClientName { get; set; }
        [Required(ErrorMessage = "Enter your address")]
        public string? Address { get; set; }
        [Required(ErrorMessage = "Enter your phone number")]
        public string? PhoneNumber { get; set; }
        [Required(ErrorMessage = "Enter your email")]
        public string? Email { get; set; }
        
        public string? Description {  get; set; }
        [Required(ErrorMessage = "Enter a date and time")]
        public DateTime DateTime { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using stonecutter.Models;
using System.Diagnostics;

namespace stonecutter.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InventoryController.cs
using Microsoft.AspNetCore.Mvc;
using stonecutter.Data;
using stonecutter.Models;

namespace stonecutter.Controllers
{
    public class InventoryController : Controller
    {
        private readonly AppDbContext _context1;
        public InventoryController(AppDbContext appDbContext)
        {
            _context1 = appDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateInventory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddInvetory(Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                _context1.Inventories.Add(inventory);
                _context1.SaveChanges();
                return RedirectToAction("ViewInventory");
            }
            else { return View(); }

        }

        [HttpGet]
        public IActionResult ViewInventory()
        {
            var list = _context1.Inventories.ToList();
            return View(list);
        }
       
       
    }
}

Controllers/TimeTableController.cs
using Microsoft.AspNetCore.Mvc;
using stonecutter.Data;
using stonecutter.Models;

namespace stonecutter.Controllers
{
    public class TimeTableController : Controller
    {
        private readonly AppDbContext _context;
        public TimeTableController(AppDbContext appDbContext)
        {
            _context = appDbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateTimeTable() {
            return View();
        }
        [HttpPost]
        public IActionResult CreateTimeTable(TimeTable timeTable)
        {
            if(ModelState.IsValid) {
                _context.TimeTables.Add(timeTable);
                _context.SaveChanges();
                return RedirectToAction("ListTimeTables");
            }
            else { return View(); }
            
        }

        [HttpGet]
        public IActionResult ListTimeTables() {
            var list = _context.TimeTables.ToList();
            return View(list);
        }
        [HttpGet]
        public IActionResult EditTimeTable()
        {
            return View();
        }
        [HttpPost]
        public IActionResult EditTimeTable(TimeTable editedTTable)
        {
            if(ModelState.IsValid)
            {
                var timeTable = _context.TimeTables.Attach(editedTTable);
                timeTable.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("ListTimeTables");
            }
            else
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult DeleteTimeTable(int id) {
            _context.TimeTables.Remove(_context.TimeTables.Find(id));
            _context.SaveChanges();
            return RedirectToAction("ListTimeTables");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Stone countertop tool estimation</h1>
    
</div>

<div>
    <a asp-action="ListTimeTables" asp-controller="TimeTable">View scheduled installations</a>
    <a asp-action="CreateInventory" asp-controller="Inventory">create Inventories</a>
    <a asp-action="ViewInventory" asp-controller="Inventory">view Inventories</a>


</div>

Views/Inventory/CreateInventory.cshtml
@model stonecutter.Models.Inventory
<html>
<body>
    <h2>Schedule Installation</h2>
    <form asp-action="AddInvetory" mrthod="post">
        <div>
            <label asp-for="Name">Name:</label>
            <input asp-for="Name" placeholder="Enter your name" />
        </div>

        <div>
            <label asp-for="StoneType">Stone Type:</label>
            <input asp-for="StoneType" placeholder="Enter your address" />
        </div>

        <div>
            <label asp-for="DateTime">Date and Time of installation:</label>
            <input asp-for="DateTime" />
        </div>

        <div>
            <label asp-for="Quantity">Quantity:</label>
            <input asp-for="Quantity" placeholder="Enter your Phone Number" />
        </div>


        <button type="submit">submit</button>
    </form>
</body>

</html>

Views/Inventory/ViewInventory.cshtml
@model IEnumerable<stonecutter.Models.Inventory>

@{

}
<!DOCTYPE html>
<html>
<body>
    <h2>List of Inventories</h2>
    <table id="timetables">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Stone Type</th>
                <th>Quantity</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (stonecutter.Models.Inventory t in Model)
            {
                <tr>
                    <td>@t.Id</td>
                    <td>@t.Name</td>
                    <td>@t.StoneType</td>
                    <td>@t.Quantity</td>
                    <td>@t.DateTime</td>
                </tr>
            }
            <tr>
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
            </tr>
        </tbody>
    </table>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - stonecutter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/stonecutter.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">stonecutter</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - stonecutter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TimeTable/CreateTimeTable.cshtml
@model stonecutter.Models.TimeTable
<html>
<body>
    <h2>Schedule Installation</h2>
    <form asp-action="CreateTimeTable" mrthod="post">
    <div>
        <label asp-for="ClientName">Name:</label>
        <input asp-for="ClientName" placeholder="Enter your name" />
    </div>

    <div>
        <label asp-for="Address">Address:</label>
        <input asp-for="Address" placeholder="Enter your address" />
    </div>

    <div>
        <label asp-for="DateTime">Date and Time of installation:</label>
        <input asp-for="DateTime" />
    </div>

    <div>
        <label asp-for="PhoneNumber">Phone Number:</label>
        <input asp-for="PhoneNumber" placeholder="Enter your Phone Number" />
    </div>

    <div>
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" placeholder="Enter your Email" />
    </div>

    <div>
        <label asp-for="Description">Description:</label>
        <input asp-for="Description" placeholder="Enter any additional information" />
    </div>
    <button type="submit">submit</button>
    </form>
</body>
    
</html>

Views/TimeTable/DeleteTimeTable.cshtml
successfully deleted
<div>
    <a href="~/TimeTable/ListTimeTable">Back to main page</a>
</div>

Views/TimeTable/EditTimeTable.cshtml
@model stonecutter.Models.TimeTable

<html>
<head>
    <link rel="stylesheet" href="/css/TimeTable.css" />
</head>
    <body>
        <h2>Edit TimeTable</h2>
    <form asp-action="EditTimeTable" mrthod="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="input-form">
            <label asp-for="ClientName">Name:</label>
            <input class="form-control" asp-for="ClientName" placeholder="Enter your name" />
            <span asp-validation-for="ClientName" class="text-danger"></span>
        </div>

        <div class="input-form">
            <label asp-for="Address">Address:</label>
            <input class="form-control" asp-for="Address" placeholder="Enter your address" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="input-form">
            <label asp-for="DateTime">Date and Time of installation:</label>
            <input class="form-control" asp-for="DateTime" />
            <span asp-validation-for="DateTime" class="text-danger"></span>
        </div>

        <div class="input-form">
            <label asp-for="PhoneNumber">Phone Number:</label>
            <input class="form-control" asp-for="PhoneNumber" placeholder="Enter your Phone Number" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>

        <div class="input-form">
            <label asp-for="Email">Email:</label>
            <input class="form-control" asp-for="Email" placeholder="Enter your Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="input-form">
            <label asp-for="Description">Description (optional):</label>
            <input class="form-control" asp-for="Description" placeholder="Enter any additional information" />
        </div>
        <button type="submit">submit</button>
    </form>
    </body>
</html>

Views/TimeTable/ListTimeTables.cshtml
@model IEnumerable<stonecutter.Models.TimeTable>
@{

}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/TimeTable.css" />
</head>
    <body>
        <h2>List of Scheduled Installations</h2>
        <table id="timetables">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone number</th>
                    <th>Email</th>
                    <th>Description</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
            @foreach (stonecutter.Models.TimeTable t in Model)
            {
                <tr>
                    <td>@t.Id</td>
                    <td>@t.ClientName</td>
                    <td>@t.Address</td>
                    <td>@t.PhoneNumber</td>
                    <td>@t.Email</td>
                    <td>@t.Description</td>
                    <td class="c-table"><a href="~/TimeTable/EditTimeTable/@t.Id" class="tbButton">Edit</a></td>
                    <td class="c-table"><a href="~/TimeTable/DeleteTimeTable/@t.Id" class="tbButton">Delete</a></td>
                </tr>
            }
            <tr>
                
            </tr>
            </tbody>
        </table>

    <a href="~/TimeTable/CreateTimeTable" class="pgButton">Schedule an installation</a>
    <a href="~/" class="pgButton">Back to Main Page</a>
    </body>
</html>